In [1]:
%run PROMETHEE_funct.ipynb

Pixiedust database opened successfully


In [2]:
import numpy as np

In [3]:
def calc_miu_v(tabel_alternatif):

    row = list()
    for index in tabel_alternatif.index:
        row_val = list()
        for column in tabel_alternatif:
            #derajat kepemilikan
            miu_x = tabel_alternatif[column][index]/100
            #derajat ketidakpemilikan
            v_x = 1-miu_x

            row_val.append([miu_x,v_x])

        row.append(row_val)

    return row

In [4]:
def entropy_mtrx(decision_matrix, df):
    entropy_matrix = np.zeros(shape=(9,len(df.columns)))

    for i in range(len(decision_matrix)):
        for idx, val in enumerate(decision_matrix[i]):
            entropy = 1-abs(val[0]-val[1])
            entropy_matrix[i][idx] = entropy

    return entropy_matrix

In [5]:
def knowledge_measure(decision_matrix, entropy_matrix):
    for i in range(len(entropy_matrix)):
        for idx, val in enumerate(entropy_matrix[0]):
            entropy_matrix[i][idx] = 1 - 0.5*(val+(1 - decision_matrix[i][idx][0] - decision_matrix[i][idx][1]))
    
    return entropy_matrix

In [6]:
def hitung_a(entropy_matrix):
    a = list()
    for index in range(len(entropy_matrix)):
        a_val = 0
        for j, val in enumerate(entropy_matrix[index]):
            if not math.isnan(val):
                a_val += val

        a.append(a_val)

    return a

In [7]:
def hitung_weight(a, weight):
    for i, val in enumerate(a):
        if i == 0:
            weight["Matematika"] = val/sum(a)
        elif i == 1:
            weight["Inggris"] = val/sum(a)
        elif i == 2:
            weight["Indonesia"] = val/sum(a)
        elif i == 3:
            weight["Fisika"] = val/sum(a)
        elif i == 4:
            weight["Kimia"] = val/sum(a)
        elif i == 5:
            weight["Biologi"] = val/sum(a)
        elif i == 6:
            weight["Ekonomi"] = val/sum(a)
        elif i == 7:
            weight["Geografi"] = val/sum(a)
        elif i == 8:
            weight["Sosiologi"] = val/sum(a)
            
    return weight

In [8]:
tabel_alternatif = open_tabel("Tabel Alternatif.csv")

tabel_alternatif

Astronomi - ITB (IPA)  \
Matematika              86.000000   
Inggris                 87.000000   
Indonesia               84.000000   
Fisika                  92.000000   
Kimia                   81.000000   
Biologi                 85.000000   
Ekonomi                 87.917424   
Geografi                85.858929   
Sosiologi               89.898990   

            Fakultas Ilmu Dan Teknologi Kebumian - ITB (IPA)  \
Matematika                                         84.000000   
Inggris                                            86.000000   
Indonesia                                          85.000000   
Fisika                                             85.000000   
Kimia                                              83.000000   
Biologi                                            88.000000   
Ekonomi                                            87.917424   
Geografi                                           85.858929   
Sosiologi                                          89.898990   

            Fakultas Teknik Sipil & Lingkungan - ITB (IPA)  \
Matematika                                       89.675336   
Inggris                                          88.522222   
Indonesia                                        87.367816   
Fisika                                           88.747126   
Kimia                                            89.188218   
Biologi                                          88.355682   
Ekonomi                                          87.917424   
Geografi                                         85.858929   
Sosiologi                                        89.898990   

            Fakultas Teknik Sipil Dan Lingkungan - ITB (IPA)  \
Matematika                                         87.891779   
Inggris                                            90.000000   
Indonesia                                          91.666667   
Fisika                                             89.666667   
Kimia                                              88.666667   
Biologi                                            87.666667   
Ekonomi                                            87.917424   
Geografi                                           85.858929   
Sosiologi                                          89.898990   

            Fakultas Teknik Sipil Dan Lingkungan (Ftsl) - ITB (IPA)  \
Matematika                                          87.000000         
Inggris                                             91.000000         
Indonesia                                           96.000000         
Fisika                                              94.000000         
Kimia                                               95.237644         
Biologi                                             88.000000         
Ekonomi                                             87.917424         
Geografi                                            85.858929         
Sosiologi                                           89.898990         

            Fakultas Teknik Sipil Dan Lingkungan-Kampus Jatinangor - ITB (IPA)  \
Matematika                                          89.675336                    
Inggris                                             88.522222                    
Indonesia                                           87.367816                    
Fisika                                              88.747126                    
Kimia                                               89.188218                    
Biologi                                             88.355682                    
Ekonomi                                             87.917424                    
Geografi                                            85.858929                    
Sosiologi                                           89.898990                    

            Fakultas Teknologi Industri - ITB (IPA)  Farmasi - ITB (IPA)  \
Matematika                                90.337668            95.000000   
Inggris                                   93.261111   

In [9]:
miu_v = calc_miu_v(tabel_alternatif)

miu_v

[[[0.86, 0.14],
  [0.84, 0.16000000000000003],
  [0.8967533577533578, 0.10324664224664215],
  [0.878917785917786, 0.12108221408221398],
  [0.87, 0.13],
  [0.8967533577533578, 0.10324664224664215],
  [0.9033766788766786, 0.09662332112332139],
  [0.95, 0.050000000000000044],
  [0.8828471870010329, 0.11715281299896707],
  [0.9224502238502237, 0.07754977614977632],
  [0.9066883394383396, 0.0933116605616604],
  [0.91, 0.08999999999999997],
  [0.92, 0.07999999999999996],
  [0.9022511192511192, 0.09774888074888077],
  [0.9007136173767752, 0.09928638262322476],
  [0.93, 0.06999999999999995],
  [0.9, 0.09999999999999998],
  [0.875, 0.125],
  [0.9, 0.09999999999999998],
  [0.98, 0.020000000000000018],
  [0.9066666666666668, 0.09333333333333316],
  [0.94, 0.06000000000000005],
  [0.83, 0.17000000000000004],
  [0.8967533577533578, 0.10324664224664215],
  [0.92, 0.07999999999999996],
  [0.91, 0.08999999999999997],
  [0.92, 0.07999999999999996],
  [0.92, 0.07999999999999996],
  [0.95, 0.050000000000

In [10]:
#bikin decision matriks
decision_matrix = np.array([miu_v[i] for i in range(len(miu_v))])

decision_matrix

array([[[0.86      , 0.14      ],
        [0.84      , 0.16      ],
        [0.89675336, 0.10324664],
        [0.87891779, 0.12108221],
        [0.87      , 0.13      ],
        [0.89675336, 0.10324664],
        [0.90337668, 0.09662332],
        [0.95      , 0.05      ],
        [0.88284719, 0.11715281],
        [0.92245022, 0.07754978],
        [0.90668834, 0.09331166],
        [0.91      , 0.09      ],
        [0.92      , 0.08      ],
        [0.90225112, 0.09774888],
        [0.90071362, 0.09928638],
        [0.93      , 0.07      ],
        [0.9       , 0.1       ],
        [0.875     , 0.125     ],
        [0.9       , 0.1       ],
        [0.98      , 0.02      ],
        [0.90666667, 0.09333333],
        [0.94      , 0.06      ],
        [0.83      , 0.17      ],
        [0.89675336, 0.10324664],
        [0.92      , 0.08      ],
        [0.91      , 0.09      ],
        [0.92      , 0.08      ],
        [0.92      , 0.08      ],
        [0.95      , 0.05      ],
        [0.91 

In [11]:
entropy_matrix = entropy_mtrx(decision_matrix, tabel_alternatif)

entropy_matrix

array([[0.28      , 0.32      , 0.20649328, 0.24216443, 0.26      ,
        0.20649328, 0.19324664, 0.1       , 0.23430563, 0.15509955,
        0.18662332, 0.18      , 0.16      , 0.19549776, 0.19857277,
        0.14      , 0.2       , 0.25      , 0.2       , 0.04      ,
        0.18666667, 0.12      , 0.34      , 0.20649328, 0.16      ,
        0.18      , 0.16      , 0.16      , 0.1       , 0.18      ,
        0.2       , 0.36      , 0.14      , 0.26794799, 0.14      ,
        0.26324664, 0.12      , 0.24      , 0.4       , 0.32324664,
        0.3       , 0.18      ],
       [0.26      , 0.28      , 0.22955556, 0.2       , 0.18      ,
        0.22955556, 0.13477778, 0.2       , 0.22675214, 0.2273037 ,
        0.20238889, 0.24      , 0.18      , 0.26318519, 0.21890058,
        0.24      , 0.2       , 0.27      , 0.18      , 0.12      ,
        0.20666667, 0.18      , 0.24      , 0.22955556, 0.24      ,
        0.24      , 0.26      , 0.22      , 0.28      , 0.14      ,
        0.16   

In [12]:
knowledge_measure_matrix = knowledge_measure(decision_matrix, entropy_matrix)

knowledge_measure_matrix

array([[0.86      , 0.84      , 0.89675336, 0.87891779, 0.87      ,
        0.89675336, 0.90337668, 0.95      , 0.88284719, 0.92245022,
        0.90668834, 0.91      , 0.92      , 0.90225112, 0.90071362,
        0.93      , 0.9       , 0.875     , 0.9       , 0.98      ,
        0.90666667, 0.94      , 0.83      , 0.89675336, 0.92      ,
        0.91      , 0.92      , 0.92      , 0.95      , 0.91      ,
        0.9       , 0.82      , 0.93      , 0.86602601, 0.93      ,
        0.86837668, 0.94      , 0.88      , 0.8       , 0.83837668,
        0.85      , 0.91      ],
       [0.57      , 0.58      , 0.55162332, 0.56054111, 0.565     ,
        0.55162332, 0.54831166, 0.525     , 0.55857641, 0.53877489,
        0.54665583, 0.545     , 0.54      , 0.54887444, 0.54964319,
        0.535     , 0.55      , 0.5625    , 0.55      , 0.51      ,
        0.54666667, 0.53      , 0.585     , 0.55162332, 0.54      ,
        0.545     , 0.54      , 0.54      , 0.525     , 0.545     ,
        0.55   

In [13]:
a = hitung_a(knowledge_measure_matrix)

a

[37.66195105671806,
 23.169024471640974,
 23.169024471640974,
 23.169024471640974,
 23.169024471640974,
 23.169024471640974,
 23.169024471640974,
 23.169024471640974,
 23.169024471640974]

In [14]:
weight = {
    "Matematika": 0,
    "Inggris": 0,
    "Indonesia": 0,
    "Fisika": 0,
    "Kimia": 0,
    "Biologi": 0,
    "Ekonomi": 0,
    "Geografi": 0,
    "Sosiologi": 0,
}

In [15]:
weight = hitung_weight(a, weight)

weight

{'Matematika': 0.1688769595654987,
 'Inggris': 0.10389038005431268,
 'Indonesia': 0.10389038005431268,
 'Fisika': 0.10389038005431268,
 'Kimia': 0.10389038005431268,
 'Biologi': 0.10389038005431268,
 'Ekonomi': 0.10389038005431268,
 'Geografi': 0.10389038005431268,
 'Sosiologi': 0.10389038005431268}