In [1]:
%run PROMETHEE_funct.ipynb

Pixiedust database opened successfully


In [2]:
import numpy as np

In [3]:
def calc_miu_v(tabel_alternatif):

    row = list()
    for index in tabel_alternatif.index:
        row_val = list()
        for column in tabel_alternatif:
            #derajat kepemilikan
            miu_x = tabel_alternatif[column][index]/100
            #derajat ketidakpemilikan
            v_x = 1-miu_x

            row_val.append([miu_x,v_x])

        row.append(row_val)

    return row

In [4]:
def entropy_mtrx(decision_matrix):
    entropy_matrix = np.zeros(shape=(9,137))

    for i in range(len(decision_matrix)):
        for idx, val in enumerate(decision_matrix[i]):
            entropy = 1-abs(val[0]-val[1])
            entropy_matrix[i][idx] = entropy

    return entropy_matrix

In [5]:
def knowledge_measure(decision_matrix, entropy_matrix):
    for i in range(len(entropy_matrix)):
        for idx, val in enumerate(entropy_matrix[0]):
            entropy_matrix[i][idx] = 1 - 0.5*(val+(1 - decision_matrix[i][idx][0] - decision_matrix[i][idx][1]))
    
    return entropy_matrix

In [6]:
def hitung_a(entropy_matrix):
    a = list()
    for index in range(len(entropy_matrix)):
        a_val = 0
        for j, val in enumerate(entropy_matrix[index]):
            if not math.isnan(val):
                a_val += val

        a.append(a_val)

    return a

In [7]:
def hitung_weight(a, weight):
    for i, val in enumerate(a):
        if i == 0:
            weight["Matematika"] = val/sum(a)
        elif i == 1:
            weight["Inggris"] = val/sum(a)
        elif i == 2:
            weight["Indonesia"] = val/sum(a)
        elif i == 3:
            weight["Fisika"] = val/sum(a)
        elif i == 4:
            weight["Kimia"] = val/sum(a)
        elif i == 5:
            weight["Biologi"] = val/sum(a)
        elif i == 6:
            weight["Ekonomi"] = val/sum(a)
        elif i == 7:
            weight["Geografi"] = val/sum(a)
        elif i == 8:
            weight["Sosiologi"] = val/sum(a)
            
    return weight

In [8]:
tabel_alternatif = open_tabel("Tabel Alternatif.csv")

tabel_alternatif

Administrasi Fiskal - UI (IPS)  Administrasi Negara - UNPAD (IPS)  \
Matematika                       84.000000                          88.500000   
Inggris                          84.000000                          80.500000   
Indonesia                        84.000000                          89.500000   
Fisika                           82.000000                          84.584430   
Kimia                            81.000000                          84.592411   
Biologi                          83.000000                          83.879942   
Ekonomi                          86.145714                          89.000000   
Geografi                         85.512727                          87.500000   
Sosiologi                        86.930877                          85.500000   

            Administrasi Niaga - UI (IPS)  Administrasi Perpajakan - UB (IPS)  \
Matematika                      85.465625                           92.000000   
Inggris                         83.888667                           86.000000   
Indonesia                       85.246032                           89.000000   
Fisika                          84.493016                           81.956615   
Kimia                           85.297674                           82.397782   
Biologi                         84.182558                           82.827536   
Ekonomi                         86.145714                           91.242143   
Geografi                        85.512727                           91.000000   
Sosiologi                       86.930877                           91.000000   

            Agribisnis - UNDIP (IPA)  Agroekoteknologi - UB (IPA)  \
Matematika                 86.250000                    81.852143   
Inggris                    85.500000                    84.729722   
Indonesia                  87.833333                    85.837917   
Fisika                     83.360000                    81.739154   
Kimia                      85.100000                    82.349446   
Biologi                    86.172727                    83.706884   
Ekonomi                    87.271429                    83.726429   
Geografi                   87.500000                    84.627747   
Sosiologi                  87.000000                    85.702500   

            Agroteknologi - UNPAD (IPA)  Akuntansi - UGM (IPS)  \
Matematika                    82.500000              91.625000   
Inggris                       82.750000              90.875000   
Indonesia                     84.000000              89.875000   
Fisika                        80.500000              89.437576   
Kimia                         81.500000              88.716106   
Biologi                       83.250000              89.695798   
Ekonomi                       82.062045              92.250000   
Geografi                      81.926031              88.959803   
Sosiologi                     81.331846              91.872475   

            Akutansi - UI (IPS)  Antropologi - UNAIR (IPS)  ...  \
Matematika            44.693125                  84.576004  ...   
Inggris               54.255467                  85.307966  ...   
Indonesia             85.000000                  85.970128  ...   
Fisika                87.000000                  84.646720  ...   
Kimia                 74.300000                  85.035214  ...   
Biologi               83.000000                  86.206897  ...   
Ekonomi               86.145714                  85.211111  ...   
Geografi              85.512727                  84.793706  ...   
Sosiologi             86.930877                  85.695971  ...   

            Teknik Sistem Perkapalan - ITS (IPA)  Teknobiomedik - UNAIR (IPA)  \
Matematika                             90.000000                    86.154669   
Inggris                                87.000000                    86.153983   
Indonesia                              88.000000                    86.651731   
Fisika                                 88.5

In [9]:
miu_v = calc_miu_v(tabel_alternatif)

miu_v

[[[0.84, 0.16000000000000003],
  [0.885, 0.11499999999999999],
  [0.85465625, 0.14534375],
  [0.92, 0.07999999999999996],
  [0.8624999999999998, 0.13750000000000018],
  [0.8185214285714288, 0.18147857142857116],
  [0.825, 0.17500000000000004],
  [0.91625, 0.08374999999999999],
  [0.44693125, 0.55306875],
  [0.8457600393916185, 0.15423996060838152],
  [0.77, 0.22999999999999998],
  [0.8773333333333332, 0.12266666666666681],
  [0.8537790697674419, 0.1462209302325581],
  [0.9, 0.09999999999999998],
  [0.86, 0.14],
  [0.86, 0.14],
  [0.8368333333333333, 0.16316666666666668],
  [0.8910294117647058, 0.10897058823529415],
  [0.8240857142857143, 0.1759142857142857],
  [0.8038972219552053, 0.1961027780447947],
  [0.8240857142857143, 0.1759142857142857],
  [0.84, 0.16000000000000003],
  [0.9, 0.09999999999999998],
  [0.8967533577533578, 0.10324664224664215],
  [0.85465625, 0.14534375],
  [0.8880392156862746, 0.11196078431372536],
  [0.83, 0.17000000000000004],
  [0.8828471870010329, 0.1171528129

In [16]:
#bikin decision matriks
decision_matrix = np.array([miu_v[i] for i in range(len(miu_v))])

decision_matrix

array([[[0.84      , 0.16      ],
        [0.885     , 0.115     ],
        [0.85465625, 0.14534375],
        ...,
        [0.85      , 0.15      ],
        [0.87      , 0.13      ],
        [0.85      , 0.15      ]],

       [[0.84      , 0.16      ],
        [0.805     , 0.195     ],
        [0.83888667, 0.16111333],
        ...,
        [0.855     , 0.145     ],
        [0.94      , 0.06      ],
        [0.85      , 0.15      ]],

       [[0.84      , 0.16      ],
        [0.895     , 0.105     ],
        [0.85246032, 0.14753968],
        ...,
        [0.865     , 0.135     ],
        [0.8       , 0.2       ],
        [0.84      , 0.16      ]],

       ...,

       [[0.86145714, 0.13854286],
        [0.89      , 0.11      ],
        [0.86145714, 0.13854286],
        ...,
        [0.86      , 0.14      ],
        [0.89837895, 0.10162105],
        [0.86      , 0.14      ]],

       [[0.85512727, 0.14487273],
        [0.875     , 0.125     ],
        [0.85512727, 0.14487273],
        .

In [11]:
entropy_matrix = entropy_mtrx(decision_matrix)

entropy_matrix

array([[0.32      , 0.23      , 0.2906875 , ..., 0.3       , 0.26      ,
        0.3       ],
       [0.32      , 0.39      , 0.32222666, ..., 0.29      , 0.12      ,
        0.3       ],
       [0.32      , 0.21      , 0.29507937, ..., 0.27      , 0.4       ,
        0.32      ],
       ...,
       [0.27708571, 0.22      , 0.27708571, ..., 0.28      , 0.20324211,
        0.28      ],
       [0.28974545, 0.25      , 0.28974545, ..., 0.27      , 0.23811356,
        0.26      ],
       [0.26138246, 0.29      , 0.26138246, ..., 0.29      , 0.19272727,
        0.3       ]])

In [17]:
knowledge_measure_matrix = knowledge_measure(decision_matrix, entropy_matrix)

knowledge_measure_matrix

array([[0.58      , 0.5575    , 0.57267187, ..., 0.575     , 0.565     ,
        0.575     ],
       [0.71      , 0.72125   , 0.71366406, ..., 0.7125    , 0.7175    ,
        0.7125    ],
       [0.71      , 0.72125   , 0.71366406, ..., 0.7125    , 0.7175    ,
        0.7125    ],
       ...,
       [0.71      , 0.72125   , 0.71366406, ..., 0.7125    , 0.7175    ,
        0.7125    ],
       [0.71      , 0.72125   , 0.71366406, ..., 0.7125    , 0.7175    ,
        0.7125    ],
       [0.71      , 0.72125   , 0.71366406, ..., 0.7125    , 0.7175    ,
        0.7125    ]])

In [13]:
a = hitung_a(knowledge_measure_matrix)

a

[116.9403655816575,
 78.52981720917121,
 78.52981720917121,
 78.52981720917121,
 78.52981720917121,
 78.52981720917121,
 78.52981720917121,
 78.52981720917121,
 78.52981720917121]

In [14]:
weight = {
    "Matematika": 0,
    "Inggris": 0,
    "Indonesia": 0,
    "Fisika": 0,
    "Kimia": 0,
    "Biologi": 0,
    "Ekonomi": 0,
    "Geografi": 0,
    "Sosiologi": 0,
}

In [15]:
weight = hitung_weight(a, weight)

weight

{'Matematika': 0.15692924889694074,
 'Inggris': 0.1053838438878824,
 'Indonesia': 0.1053838438878824,
 'Fisika': 0.1053838438878824,
 'Kimia': 0.1053838438878824,
 'Biologi': 0.1053838438878824,
 'Ekonomi': 0.1053838438878824,
 'Geografi': 0.1053838438878824,
 'Sosiologi': 0.1053838438878824}